-- 관리 화면에서만 등록했거나 이름을 바꿔 저장소 사본과 달라진 행의 영문 칸 (AI 번역, 2026-10-01).
-- 원문은 .github/workflows/en-missing.yml 이 운영 DB 에서 읽어 로그로 남긴 값이다.
-- 영문 칸이 비어 있을 때만 채워, 다시 적용해도 관리 화면에서 고친 값을 덮지 않는다.

-- 필름 31종
UPDATE public.films SET description_en = $en$Adox's ultra-low-speed black-and-white film, made by adapting a microfilm emulsion for photography. Its monodisperse emulsion delivers resolution where grain all but disappears, and it is a frequent pick for big enlargements and copy work. It only reaches its full spec when paired with the dedicated Adotech II/III developer.$en$ WHERE slug = 'adoxcms20' AND description_en IS NULL;
UPDATE public.films SET description_en = $en$A black-and-white slide film made by reversal-processing Adox's Silvermax base. Rated ISO 160 in daylight, it can also be shot as a negative at ISO 80 to 100. Clear triacetate base with an anti-halation layer. Supply is limited since Silvermax was discontinued.$en$ WHERE slug = 'adoxscala160' AND description_en IS NULL;
UPDATE public.films SET description_en = $en$A black-and-white slide film made by reversal-processing Adox's HR-50 base. Ultra-fine grain, a clear base and super-panchromatic sensitivity suit it to projection. Process it at a dedicated reversal lab such as dr5 or with a home reversal kit. 35mm, 36 exposures.$en$ WHERE slug = 'adoxscala50' AND description_en IS NULL;
UPDATE public.films SET description_en = $en$A traditional silver-rich black-and-white negative known for wide exposure latitude and rich tonality. It is the base Adox Scala 160 is made from, and it is now discontinued or in limited supply. It turns up a roll at a time when leftover stock appears.$en$ WHERE slug = 'adoxsilvermax100' AND description_en IS NULL;
UPDATE public.films SET description_en = $en$auroer film 400 is a 35mm color film from the Korean brand Auroer. An ISO 400 film for everyday snaps, travel and casual records, it is made so that people just starting out with film cameras can use it without worry.$en$ WHERE slug = 'auroer400d' AND description_en IS NULL;
UPDATE public.films SET description_en = $en$auroer 800T is Auroer's ISO 800 tungsten color film. A 35mm, 36-exposure roll, it is sold as a cinema film that any regular color lab can develop in C-41. It shines at night, indoors and under neon or tungsten light, where color temperature runs low, and the results lean toward a cool, cinematic tone rather than warm yellows.$en$ WHERE slug = 'auroer800t' AND description_en IS NULL;
UPDATE public.films SET description_en = $en$A black-and-white reversal film from Foma in the Czech Republic. Often named as the closest replacement for the discontinued Agfa Scala, it comes in 35mm 36-exposure rolls as well as 8mm and Super 16mm cine formats. It needs the dedicated R-100 reversal process and cannot go through regular negative development.$en$ WHERE slug = 'fomapanr100' AND description_en IS NULL;
UPDATE public.films SET description_en = $en$An ISO 200 color negative Fujifilm released for point-and-shoot cameras in the Korean market in the 1990s. With a box labeled only in Korean, it became a Korea-only line and is now discontinued.$en$ WHERE slug = 'fujiototo200' AND description_en IS NULL;
UPDATE public.films SET description_en = $en$An intermediate stock used for duplication in film post-production. Because it is used to strike master positives from the original camera negative, its speed is extremely low. Kodak does not publish an ISO, and sellers who respool it into 135 suggest EI 0.8 to 3. It is tungsten balanced and properly processed in ECN-2, and because 2242 is on an ESTAR base it has no remjet. A tripod and bright light are practically a must.$en$ WHERE slug = 'kodak2242' AND description_en IS NULL;
UPDATE public.films SET description_en = $en$Launched in 1986 as Kodacolor VR-G 100, it was renamed Kodacolor Gold 100 in 1989 and Kodak Gold 100 in 1997, carrying Kodak's consumer color line. Discontinued in the early 2000s, it now survives only as frozen stock. It was released in both 35mm and 120.$en$ WHERE slug = 'kodakgold100' AND description_en IS NULL;
UPDATE public.films SET description_en = $en$The ISO 800 color negative inside Kodak's FunSaver disposable cameras. It belongs to the Gold family and has also been sold as loose rolls. The grain is fine for an 800, and it works well indoors or at night with flash. Standard C-41 processing.$en$ WHERE slug = 'kodakgt800' AND description_en IS NULL;
UPDATE public.films SET description_en = $en$The standard 50D daylight stock on Hollywood film sets. ECN-2 is the proper route, but with the remjet removed it can also go through C-41.$en$ WHERE slug = 'kodakvision350d' AND description_en IS NULL;
UPDATE public.films SET description_en = $en$An ISO 400 color negative from China's Lucky. Standard C-41 processing, in 35mm 36-exposure rolls. It is the faster sibling of Color 200 in the same line. With lower saturation than Kodak and a slight cool lean, it gets called cinematic. The grain shows, as you would expect from a 400, but it sits evenly, closer to Fuji Superia.$en$ WHERE slug = 'luckyxolor400' AND description_en IS NULL;
UPDATE public.films SET description_en = $en$A cine film repackaged by Japan's MARIX since 2021. It takes Kodak Vision3 50D (5203), strips the remjet backing and turns it into a roll any C-41 lab can develop. The base is an ISO 50 motion picture film, but with the remjet removed the recommended speed is ISO 100. An entry-level way to bring a light touch of cinema tone to midday sun.$en$ WHERE slug = 'marix100d' AND description_en IS NULL;
UPDATE public.films SET description_en = $en$Kodak Vision3 250D (5207) with the remjet stripped off. Because it develops in C-41, even neighborhood photo shops will take this cine film, and with the remjet removed its recommended speed sits one stop above the base at ISO 400. Often mentioned for bringing a controlled, cinematic color to bright outdoor daylight.$en$ WHERE slug = 'marix400d' AND description_en IS NULL;
UPDATE public.films SET description_en = $en$Built on Kodak Vision3 500T (5219), with the remjet removed for C-41 compatibility. Balanced for tungsten light (3200K), it turns bluish under daylight, and that tone has become its trademark. One of the films named most often for city scenes at night and interior reportage under artificial light.$en$ WHERE slug = 'marix800t' AND description_en IS NULL;
UPDATE public.films SET description_en = $en$A low-speed line made from Kodak Vision3 5203 (50D) with the remjet removed. Grain is almost invisible and the colors run saturated, and it is a frequent pick for harsh midday sun and landscapes. C-41.$en$ WHERE slug = 'reflxlab50d' AND description_en IS NULL;
UPDATE public.films SET description_en = $en$Fujifilm's consumer E-6 slide film. It was known for well-controlled daylight color, and the entire Sensia line was discontinued in 2010. Today it only turns up on the used market and as frozen stock.$en$ WHERE slug = 'sensia100' AND description_en IS NULL;
UPDATE public.films SET description_en = $en$The middle speed of the Sensia line. A balanced E-6 slide film for everyday snaps and travel, discontinued in 2010 along with the rest of the line.$en$ WHERE slug = 'sensia200' AND description_en IS NULL;
UPDATE public.films SET description_en = $en$The fastest speed in the Sensia line. It made E-6 slides possible indoors and in low light, was often mentioned for landscape reportage, and was discontinued in 2010 along with the rest of the line.$en$ WHERE slug = 'sensia400' AND description_en IS NULL;
UPDATE public.films SET description_en = $en$A limited-edition consumer color negative from Silberra, ISO 100. C-41 processing.$en$ WHERE slug = 'silberracolor100' AND description_en IS NULL;
UPDATE public.films SET description_en = $en$A consumer color negative Silberra released in 2021, ISO 160. C-41 processing, with a warm tone.$en$ WHERE slug = 'silberracolor160' AND description_en IS NULL;
UPDATE public.films SET description_en = $en$A limited-edition consumer color negative Silberra announced in 2021, ISO 50. C-41 processing, with a warm tone.$en$ WHERE slug = 'silberracolor50' AND description_en IS NULL;
UPDATE public.films SET description_en = $en$Silberra's orthochromatic black-and-white negative, ISO 50. Because it is not sensitive to red, skin and lips render darker in a classic grayscale.$en$ WHERE slug = 'silberraorta50' AND description_en IS NULL;
UPDATE public.films SET description_en = $en$Silberra's orthochromatic black-and-white negative, ISO 80. Its grayscale is a step softer and its latitude a little wider.$en$ WHERE slug = 'silberraorta80' AND description_en IS NULL;
UPDATE public.films SET description_en = $en$Silberra's panchromatic black-and-white negative, ISO 100. The standard speed of the PAN series, and the same emulsion is also sold as Ultima 100.$en$ WHERE slug = 'silberrapan100' AND description_en IS NULL;
UPDATE public.films SET description_en = $en$Silberra's panchromatic black-and-white negative, ISO 160. Also sold as Ultima 160, with grain that feels rough yet calm.$en$ WHERE slug = 'silberrapan160' AND description_en IS NULL;
UPDATE public.films SET description_en = $en$Silberra's limited-edition panchromatic black-and-white negative, ISO 200. Also sold as Ultima 200.$en$ WHERE slug = 'silberrapan200' AND description_en IS NULL;
UPDATE public.films SET description_en = $en$A panchromatic black-and-white negative, ISO 50, from the Russian brand Silberra. Known for fine grain and high resolution, and the same emulsion is also sold in premium packaging as Ultima 50.$en$ WHERE slug = 'silberrapan50' AND description_en IS NULL;
UPDATE public.films SET description_en = $en$Silberra's budget black-and-white negative, starting from the same base as Ultima. Beyond its standard ISO 200 exposure, it holds up well pushed or pulled to 100 or 400.$en$ WHERE slug = 'silberrau200' AND description_en IS NULL;
UPDATE public.films SET description_en = $en$The ISO 400 black-and-white negative in Silberra's U series. Built on the same base, a budget line with room to push.$en$ WHERE slug = 'silberrau400' AND description_en IS NULL;

-- 현상소 2곳 (name·region 원문으로 찾는다)
UPDATE public.labs SET name_en = COALESCE(name_en, $en$Camera Photo Studio$en$), address_en = COALESCE(address_en, $en$2F, 11-13 Seongmal-ro 44beon-gil, Namdong-gu, Incheon$en$), features_en = COALESCE(features_en, $en$Darkroom experience available.$en$) WHERE name = '카메라사진관' AND region = '인천';
UPDATE public.labs SET name_en = COALESCE(name_en, $en$Haedanghwa Photo Studio$en$), address_en = COALESCE(address_en, $en$1F, 288 Jemullyang-ro, Jung-gu, Incheon$en$), features_en = COALESCE(features_en, $en$Color development 5,000 won (13,000 won for 3 rolls), high-resolution scan option, black-and-white development and scan 12,000 won. Also works as an ID photo studio.$en$) WHERE name = '해당화사진관' AND region = '인천';

-- 수리점 9곳
UPDATE public.repair_shops SET name_en = COALESCE(name_en, $en$Korea Camera$en$), address_en = COALESCE(address_en, $en$Room 502, Daehan Bldg. (Fromdoors), 408 Ilsan-ro, Ilsandong-gu, Goyang-si$en$), specialty_en = COALESCE(specialty_en, $en$Hasselblad$en$), description_en = COALESCE(description_en, $en$Hasselblad specialist.
Reopened in Ilsan after closing.$en$) WHERE name = '한국카메라' AND region = '경기';
UPDATE public.repair_shops SET name_en = COALESCE(name_en, $en$Shin Camera$en$), address_en = COALESCE(address_en, $en$2F, 47 Nampo-gil, Jung-gu, Busan$en$), specialty_en = COALESCE(specialty_en, $en$Nikon, Olympus, Contax$en$), description_en = COALESCE(description_en, $en$Repairs Olympus PEN F and FT, Contax cables and more.
2-year after-sales warranty, text consultations, parcel drop-off, and card payment accepted.$en$) WHERE name = '신카메라' AND region = '부산';
UPDATE public.repair_shops SET name_en = COALESCE(name_en, $en$Defocus$en$), address_en = COALESCE(address_en, $en$Room 302, 3F, 10-1 Namdaemun-ro, Jung-gu, Seoul$en$), specialty_en = COALESCE(specialty_en, $en$Lens cleaning, complex repairs$en$), description_en = COALESCE(description_en, $en$Defocusopt specializes in optical axis alignment and repair for Canon and Nikon DSLR lenses.
Tricky jobs such as lens haze, balsam separation and focus calibration, large-aperture lens cleaning, flashes and electronic circuits. It even machines parts on a lathe and milling machine.$en$) WHERE name = '디포커스' AND region = '서울';
UPDATE public.repair_shops SET name_en = COALESCE(name_en, $en$Bogosa$en$), address_en = COALESCE(address_en, $en$Room 110, Techno Wing, Sewoon Square, 109 Changgyeonggung-ro, Jongno-gu, Seoul$en$), specialty_en = COALESCE(specialty_en, NULL), description_en = COALESCE(description_en, NULL) WHERE name = '보고사' AND region = '서울';
UPDATE public.repair_shops SET name_en = COALESCE(name_en, $en$Segye Camera Repair Center$en$), address_en = COALESCE(address_en, $en$Room 139, Techno Wing, Sewoon Square, 109 Changgyeonggung-ro, Jongno-gu, Seoul$en$), specialty_en = COALESCE(specialty_en, NULL), description_en = COALESCE(description_en, NULL) WHERE name = '세계카메라수리센터' AND region = '서울';
UPDATE public.repair_shops SET name_en = COALESCE(name_en, $en$Speed Camera$en$), address_en = COALESCE(address_en, $en$Room 301, 3F, 2-1 Namdaemun-ro, Jung-gu, Seoul$en$), specialty_en = COALESCE(specialty_en, $en$Compact point-and-shoots$en$), description_en = COALESCE(description_en, $en$Friendly, well priced and thorough. Lately there is a bit of a backlog, though.$en$) WHERE name = '스피드카메라' AND region = '서울';
UPDATE public.repair_shops SET name_en = COALESCE(name_en, $en$Chungmuro Camera A/S$en$), address_en = COALESCE(address_en, $en$3F, 13 Supyo-ro, Jung-gu, Seoul$en$), specialty_en = COALESCE(specialty_en, NULL), description_en = COALESCE(description_en, $en$Parcel service available.$en$) WHERE name = '충무로카메라A/S' AND region = '서울';
UPDATE public.repair_shops SET name_en = COALESCE(name_en, $en$Handoksa$en$), address_en = COALESCE(address_en, $en$Shop 366, Underground Arcade, 131 Euljiro, Jung-gu, Seoul$en$), specialty_en = COALESCE(specialty_en, NULL), description_en = COALESCE(description_en, $en$You can also buy point-and-shoot cameras here.$en$) WHERE name = '한독사' AND region = '서울';
UPDATE public.repair_shops SET name_en = COALESCE(name_en, $en$Jungang Camera$en$), address_en = COALESCE(address_en, $en$Unit 3, 1F, 7 Joyang-ro, Hongseong-eup, Hongseong-gun, Chungcheongnam-do$en$), specialty_en = COALESCE(specialty_en, $en$Leica, manual rangefinders$en$), description_en = COALESCE(description_en, $en$Run by master technician Kim Hak-won. Expect a wait and higher costs, but the quality is top-notch.$en$) WHERE name = '중앙카메라' AND region = '충남';
